# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(blank=True, max_length=10000, null=True, unique=True)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('category', models.CharField(blank=True, choices=[('High (Accept)', 'High (Accept)'), ('Low (Reject)', 'Low (Reject)'), ('Null (Accept)', 'Null (Accept)')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(blank=True, max_length=10000, null=True, unique=True)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('category', models.CharField(blank=True, choices=[('Angry', 'Angry'), ('Enquiry', 'Enquiry'), ('Holiday Greeting', 'Holiday Greeting'), ('Marketing', 'Marketing')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='friends_family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(blank=True, max_length=10000, null=True, unique=True)),
                ('stories', models.TextField(blank=True, max_length=10000, null=True)),
                ('category', models.CharField(blank=True, choices=[('Greetings', 'Greetings'), ('Congrats', 'Congrats'), ('Birthday', 'Birthday'), ('Get well soon', 'Get well soon')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_acceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(blank=True, max_length=10000, null=True, unique=True)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('category', models.CharField(blank=True, choices=[('Ask salary', 'Ask salary'), ('Job requirements', 'Job requirements')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(blank=True, max_length=10000, null=True, unique=True)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('category', models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Decline', 'Decline')], max_length=100, null=True)),
            ],
        ),
    ]
