# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20161229_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends_and_family',
            old_name='stories',
            new_name='content',
        ),
    ]
