# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='stories',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
