# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20161223_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='questions',
            field=models.TextField(blank=True, max_length=10000, null=True, unique=True),
        ),
    ]
