# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20161223_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='question_order',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='question_order',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
