# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20161223_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
