# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('Something changing', 'Something changing'), ('Pathetic Occurrence About To Happen', 'Pathetic Occurrence About To Happen'), ('Gist', 'Gist'), ('Good News (Anticipated)', 'Good News (Anticipated)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='questions',
            field=models.TextField(blank=True, max_length=10000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='stories',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
